### PR TITLE
added boilerplate

### PR DESCRIPTION
**Pull request by ThomasLiARDJAVA**
# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- made the boilerplate

## Checklist

Remove any items which are not applicable.

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tested my program thoroughly

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| Screen Shot 2021-06-28 at 7 26 19 PM |
| [TODO Screenshot Link] |

### CODE REVIEW

**Review by YuyusanK — CHANGES_REQUESTED** [review]
new file with your name please

**Review by Eldar827 — APPROVED** [review]
lgtm

**Review by samuelng678 — APPROVED** [review]
lgtm

**Review by anguyen698 — APPROVED** [review]
lgtm

**Pull request merged**
