### PR TITLE
Feature/spots page

### PR DESCRIPTION
**Pull request by samuelng678**
# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- Developed lots page with link to spots page which has also been developed.
## Checklist

Remove any items which are not applicable.

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

Screen Shot 2021-08-16 at 16 30 18
Screen Shot 2021-08-16 at 16 30 10

### CODE REVIEW

**Comment by samuelng678** [comment]
^Sorry, I forgot to add the variable title. I'll do that now.

**Review by YuyusanK — APPROVED** [review]
lgtm

**Review by Eldar827 — APPROVED** [review]
lgtm

**Review by anguyen698 — APPROVED** [review]
lgtm

**Pull request merged**
